# docker build --rm -t oe_flask_sample -f Dockerfile_flaskr .
# docker run -dit -p 5000:5000 --link redis-server --link  rabbit-server --name oe_flask_sample oe_flask_sample
FROM ubuntu:16.04
MAINTAINER Omer Eisenberg "one4@nist.gov"
RUN apt-get update
RUN apt-get install -y python-pip python-dev build-essential
RUN apt-get install -y vim man lynx
RUN pip install --upgrade pip
COPY . /app
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install flask-login
RUN pip install flask-openid
RUN pip install flask-mail
RUN pip install sqlalchemy
RUN pip install flask-sqlalchemy
RUN pip install sqlalchemy-migrate
RUN pip install flask-whooshalchemy==0.55a
RUN pip install flask-wtf
RUN pip install pytz
RUN pip install flask-babel
RUN pip install flup
#ENTRYPOINT ["python"]
#CMD ["web/web_app.py"]
