# docker run -d -t --rm --name slurm_l agave_slurm
# docker exec -i -t slurm_l bash
FROM ubuntu:16.04

#MAINTAINER Rion Dooley <dooley@tacc.utexas.edu>

RUN apt-get update && apt-get install -y build-essential
RUN apt-get install -y man
RUN apt-get install -y vim
# Add slurm user
RUN useradd -ms /bin/bash slurm
#RUN adduser slurm -home /home/slurm
#    echo "slurm:slurm" | chpasswd
# USER slurm
RUN mkdir /home/slurm/.ssh
#ADD ssh/id_rsa.pub /home/slurm/.ssh/authorized_keys
USER root

# Install slurm
RUN apt-get -y install gcc
RUN apt-get -y install g++
RUN apt-get -y install python
RUN apt-get -y install make
RUN apt-get -y install munge
#RUN ["/bin/bash", "-c", "apt-get -y install munge-devel"]
#RUN ["/bin/bash", "-c", "apt-get -y install httpd"]
RUN ["/bin/bash", "-c", "apt-get -y install apache2"]
RUN apt-get -y install bzip2
RUN apt-get -y install vim
RUN apt-get -y install tar
RUN apt-get -y install perl
RUN ["/bin/bash", "-c", "/usr/bin/apt-get -y install git"]
# RUN apt-get -y install gcc gcc-g++ make munge munge-devel httpd bzip2 vim-minimal tar perl git

RUN create-munge-key

# Install slurm
WORKDIR /usr/local
RUN git clone https://github.com/SchedMD/slurm.git
WORKDIR /usr/local/slurm
RUN git checkout tags/slurm-14-03-9-1

RUN ./configure --prefix=/usr --sysconfdir=/etc/sysconfig/slurm --with-mysql_config=/usr/local/bin
RUN make
RUN make install

RUN mkdir -p /etc/sysconfig/slurm
RUN cp etc/init.d.slurm /etc/init.d/slurmd
RUN chmod +x /etc/init.d/slurmd
#RUN cp -rf doc/html /var/www/html/slurm
#RUN chown -R apache:apache /var/www/html/slurm

RUN chown -R root:root /var/log/munge
RUN chown -R root:root /var/lib/munge
RUN mkdir /var/run/munge
RUN chown -R root:root /var/run/munge
RUN chown -R root:root /etc/munge


