FROM ubuntu:16.04

#MAINTAINER Rion Dooley <dooley@tacc.utexas.edu>

RUN apt-get update && apt-get install -y build-essential
RUN apt-get install -y man
RUN apt-get install -y vim
# Add slurm user
RUN useradd -ms /bin/bash slurm
#RUN adduser slurm -home /home/slurm
#    echo "slurm:slurm" | chpasswd
# USER slurm
RUN mkdir /home/slurm/.ssh
#ADD ssh/id_rsa.pub /home/slurm/.ssh/authorized_keys
USER root

# Install slurm
#RUN yum -y install gcc gcc-g++ make munge munge-devel httpd bzip2 vim-minimal tar perl git


#--disabled-password