docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/Makefile .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/Makefile.am .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/Makefile.in .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/Slurm_Entity.pdf .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/Slurm_Individual.pdf .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/accounting.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/accounting.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/accounting_storageplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/accounting_storageplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/acct_gather_energy_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/acct_gather_energy_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/acct_gather_profile_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/acct_gather_profile_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/add.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/add.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/allocation_pies.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/api.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/api.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/arch.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/authplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/authplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/bb_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/bb_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/big_sys.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/big_sys.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/bluegene.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/bluegene.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/bull.jpg .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/burst_buffer.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/burst_buffer.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cgroups.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cgroups.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/checkpoint_blcr.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/checkpoint_blcr.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/checkpoint_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/checkpoint_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/coding_style.pdf .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/configurator.easy.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/configurator.easy.html.in .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/configurator.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/configurator.html.in .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cons_res.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cons_res.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cons_res_share.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cons_res_share.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/contributor.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/contributor.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/core_spec.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/core_spec.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/core_spec_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/core_spec_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cpu_management.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cpu_management.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cray.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cray.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cray_alps.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/cray_alps.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/crypto_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/crypto_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/disclaimer.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/disclaimer.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/dist_plane.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/dist_plane.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/documentation.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/documentation.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/download.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/download.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/dynalloc.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/elastic_computing.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/elastic_computing.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/entities.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/example_usage.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/ext_sensorsplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/ext_sensorsplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/fair_tree.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/fair_tree.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/faq.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/faq.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/footer.txt .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/gang_scheduling.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/gang_scheduling.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/gres.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/gres.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/gres_design.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/gres_design.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/gres_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/gres_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/hdf5_job_outline.png .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/hdf5_profile_user_guide.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/hdf5_profile_user_guide.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/hdf5_task_attr.png .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/header.txt .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/high_throughput.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/high_throughput.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/ibm-pe.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/ibm-pe.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/ibm.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/ibm.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/ibm_pe_fig1.png .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/ibm_pe_fig2.png .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/intel_knl.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/intel_knl.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_array.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_array.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_container_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_container_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_exit_code.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_exit_code.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_launch.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_launch.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_submit_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/job_submit_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/jobacct_gatherplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/jobacct_gatherplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/jobcompplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/jobcompplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/k_function.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/launch_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/launch_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/licenses.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/licenses.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/linuxstyles.css .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mail.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mail.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/man_index.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/man_index.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/maui.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/maui.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mc_support.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mc_support.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mc_support.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mcs.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mcs.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mcs_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mcs_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/meetings.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/meetings.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/moab.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/moab.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mpi_guide.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mpi_guide.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mpiplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/mpiplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/multi_cluster.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/multi_cluster.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/news.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/news.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/node_features_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/node_features_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/overview.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/overview.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plane_ex1.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plane_ex2.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plane_ex3.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plane_ex4.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plane_ex5.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plane_ex6.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plane_ex7.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/platforms.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/platforms.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/power_mgmt.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/power_mgmt.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/power_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/power_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/power_save.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/power_save.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/preempt.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/preempt.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/preemption_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/preemption_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/priority_multifactor.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/priority_multifactor.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/priority_multifactor3.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/priority_multifactor3.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/priority_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/priority_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/proctrack_plugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/proctrack_plugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/programmer_guide.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/programmer_guide.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/prolog_epilog.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/prolog_epilog.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/publications.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/publications.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/qos.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/qos.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/quickstart.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/quickstart.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/quickstart_admin.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/quickstart_admin.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/registration.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/reservations.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/reservations.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/resource_limits.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/resource_limits.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/rosetta.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/rosetta.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/rosetta.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/route_plugin.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/route_plugin.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/rpc.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/rpc.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/sched_config.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/sched_config.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/schedmd.png .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/schedplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/schedplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/select_design.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/select_design.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/selectplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/selectplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/shtml2html.py .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurm.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurm.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurm_design.pdf .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurm_logo.png .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurm_ug_agenda.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurm_ug_agenda.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurm_ug_cfp.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurm_ug_cfp.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurmctld_plugstack.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurmctld_plugstack.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/slurmstyles.css .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/sponsors.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/switchplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/switchplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/taskplugins.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/taskplugins.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/team.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/team.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/testimonials.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/testimonials.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/topo_ex1.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/topo_ex2.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/topology.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/topology.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/topology_plugin.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/topology_plugin.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/tres.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/tres.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/troubleshoot.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/troubleshoot.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/tutorial_intro_files.tar .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/tutorials.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/tutorials.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/usage_pies.gif .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/user_permissions.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/user_permissions.shtml .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/wckey.html .
docker cp ddhpc_ctld:/opt/slurm-16.05.3/doc/html/wckey.shtml .
