FROM ubuntu:16.04
MAINTAINER Ole Weidner <ole.weidner@ed.ac.uk>

ENV SLURM_VER=16.05.3

# Create users, set up SSH keys (for MPI)
RUN useradd -u 2001 -d /home/slurm slurm
RUN useradd -u 6000 -ms /bin/bash ddhpc

COPY etc_sudoers_ddhpc.add /etc/sudoers.d/ddhpc
# ADD etc/sudoers.d/ddhpc /etc/sudoers.d/ddhpc
COPY home_ddhpc_.ssh_config.add /home/ddhpc/.ssh/config
# ADD home/ddhpc/ssh/config /home/ddhpc/.ssh/config
COPY home_ddhpc_ssh_id_rsa.add /home/ddhpc/.ssh/id_rsa
#ADD home/ddhpc/ssh/id_rsa /home/ddhpc/.ssh/id_rsa

COPY home_ddhpc_ssh_id_rsa.pub.add /home/ddhpc/.ssh/id_rsa.pub
#ADD home/ddhpc/ssh/id_rsa.pub /home/ddhpc/.ssh/id_rsa.pub

COPY home_ddhpc_ssh_authorized_keys.add /home/ddhpc/.ssh/authorized_keys
#ADD home/ddhpc/ssh/authorized_keys /home/ddhpc/.ssh/authorized_keys

RUN chown -R ddhpc:ddhpc /home/ddhpc/.ssh/
RUN chmod 400 /home/ddhpc/.ssh/*

# Install packages
RUN apt-get update && apt-get -y  dist-upgrade
RUN apt-get install -y munge curl gcc make bzip2 supervisor python python-dev \
    libmunge-dev libmunge2 lua5.3 lua5.3-dev libopenmpi-dev openmpi-bin \
    gfortran vim python-mpi4py python-numpy python-psutil sudo psmisc \
    software-properties-common python-software-properties iputils-ping \
    openssh-server openssh-client


# Download, compile and install SLURM
RUN mkdir /home/slurm
RUN cd /home/slurm && wget https://download.schedmd.com/slurm/slurm-17.11.5.tar.bz2
RUN tar x -f /home/slurm/slurm-17.11.5.tar.bz2 -C /home/slurm

RUN cd /home/slurm/slurm-17.11.5 && ./configure && make && make install
