#FROM datadrivenhpc/slurmbase
FROM slurm_base
#FROM datadrivenhpc/slurmbase-local

MAINTAINER Ole Weidner <ole.weidner@ed.ac.uk>

COPY root_start_sh.add /root/start.sh
#ADD scripts/start.sh /root/start.sh
RUN chmod +x /root/start.sh

COPY etc_supervisor_conf_d_slurmctld_conf.add /etc/supervisor/conf.d/slurmctld.conf
#ADD etc/supervisord.d/slurmctld.conf /etc/supervisor/conf.d/slurmctld.conf

CMD ["/bin/bash","/root/start.sh"]
