#Source: https://github.com/giantswarm/celery-flower/blob/master/Dockerfile
# docker run --name gs_flower --link rabbit-server --broker="amqp://rabbit-server:5672" --broker_api="http://guest:guest@rabbit-server:15672/api/" gs_flower
# docker run --name gs_flower --link rabbit-server --broker="amqp://rabbit-server:5672" --broker_api="http://guest:guest@rabbit-server:15672/api/" gs_flower
# docker build -t gs_flower -f Dockerfile_celery_flower .

FROM ubuntu:16.04
#FROM debian:wheezy

MAINTAINER Marian Steinbach <marian@giantswarm.io>

ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONUNBUFFERED true

RUN apt-get -qq update
RUN apt-get install -y python2.7
RUN apt-get install -y python2.7-dev
RUN apt-get install -y gcc
RUN apt-get install -y python-pip

RUN pip install --upgrade pip
RUN pip install requests
RUN pip install celery
#RUN pip install flower

EXPOSE 5555

#ENTRYPOINT ["celery", "flower"]
