#FROM ubuntu:16.04

FROM python:3.5.1-alpine

# docker build --rm -f Dockerfile.1 -t flower_totem.1  .
# docker run -h flower_totem --name flower_totem --link oe_celery --link redis-server --link rabbit-server -it -d flower_totem
# docker run -it --rm --name flower_totem -p 5555:5555 flower_totem
#FROM python:3.5.1-alpine

# Source: https://github.com/totem/celery-flower-docker/blob/develop/Dockerfile

ENV DEBIAN_FRONTEND noninteractive
#ENV ETCDCTL_VERSION v2.2.5
ENV DUMB_INIT_VERSION 1.0.1

